export const ARGENTINA_PROVINCES = [
  'Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Ciudad Autónoma de Buenos Aires',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán',
]

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  'Buenos Aires': [
    'La Plata', 'Mar del Plata', 'Quilmes', 'Lanús', 'Lomas de Zamora',
    'Almirante Brown', 'La Matanza', 'Morón', 'Tigre', 'San Isidro',
    'Vicente López', 'Avellaneda', 'Bahía Blanca', 'Tandil', 'Zárate',
    'Campana', 'Pilar', 'Merlo', 'Moreno', 'San Justo', 'Florencio Varela',
    'Berazategui', 'Esteban Echeverría', 'Tres de Febrero', 'General San Martín',
    'San Fernando', 'San Miguel', 'Malvinas Argentinas', 'José C. Paz',
    'Ezeiza', 'Hurlingham', 'Ituzaingó', 'Berisso', 'Ensenada',
    'Luján', 'Mercedes', 'Chascomús', 'Dolores', 'Azul', 'Olavarría',
    'Junín', 'Pergamino', 'Trenque Lauquen', 'Pehuajó', 'Chivilcoy',
    'Necochea', 'Tres Arroyos', 'Coronel Suárez', 'Balcarce',
    'General Pueyrredón', 'Quilmes Centro', 'Bernal', 'Wilde',
  ],
  'Ciudad Autónoma de Buenos Aires': [
    'Almagro', 'Balvanera', 'Barracas', 'Belgrano', 'Boedo',
    'Caballito', 'Chacarita', 'Coghlan', 'Colegiales', 'Constitución',
    'Flores', 'Floresta', 'La Boca', 'La Paternal', 'Liniers',
    'Mataderos', 'Microcentro', 'Monte Castro', 'Montserrat',
    'Nueva Pompeya', 'Núñez', 'Palermo', 'Parque Avellaneda',
    'Parque Chacabuco', 'Parque Chas', 'Parque Patricios', 'Puerto Madero',
    'Recoleta', 'Retiro', 'Saavedra', 'San Cristóbal', 'San Nicolás',
    'San Telmo', 'Versalles', 'Villa Crespo', 'Villa del Parque',
    'Villa Devoto', 'Villa Lugano', 'Villa Luro', 'Villa Ortúzar',
    'Villa Pueyrredón', 'Villa Real', 'Villa Riachuelo', 'Villa Santa Rita',
    'Villa Soldati', 'Villa Urquiza', 'Villa Vélez Sarsfield',
  ],
  'Córdoba': [
    'Córdoba', 'Villa María', 'Río Cuarto', 'San Francisco', 'Alta Gracia',
    'Jesús María', 'Villa Carlos Paz', 'Bell Ville', 'Marcos Juárez',
    'Villa Allende', 'Cosquín', 'La Calera', 'Río Tercero', 'Oncativo',
    'Río Segundo', 'Dean Funes', 'Cruz del Eje', 'Laboulaye',
    'Leones', 'Morrison', 'Pilar', 'Villa Dolores', 'Cruz Alta',
    'James Craik', 'Oliva', 'Arroyito', 'Despeñaderos',
  ],
  'Santa Fe': [
    'Rosario', 'Santa Fe', 'Rafaela', 'Venado Tuerto', 'San Lorenzo',
    'Reconquista', 'Casilda', 'Villa Constitución', 'Firmat', 'Gálvez',
    'Esperanza', 'Santo Tomé', 'Capitán Bermúdez', 'Cañada de Gómez',
    'Carcarañá', 'Las Rosas', 'Rufino', 'Vera', 'Tostado',
    'Sunchales', 'Laguna Paiva', 'Correa', 'Armstrong', 'Pérez',
  ],
  'Mendoza': [
    'Mendoza', 'San Rafael', 'Maipú', 'Luján de Cuyo', 'Godoy Cruz',
    'Guaymallén', 'Las Heras', 'Rivadavia', 'Tunuyán', 'General Alvear',
    'Junín', 'La Paz', 'Malargüe', 'San Martín', 'Santa Rosa',
    'Lavalle', 'Palmira',
  ],
  'Tucumán': [
    'San Miguel de Tucumán', 'Yerba Buena', 'Tafí Viejo', 'Concepción',
    'Banda del Río Salí', 'Aguilares', 'Alderetes', 'Famaillá',
    'Monteros', 'Lules', 'Bella Vista', 'Simoca', 'Graneros',
  ],
  'Salta': [
    'Salta', 'Orán', 'Tartagal', 'Metán', 'Rosario de la Frontera',
    'Güemes', 'Cerrillos', 'General Güemes', 'Cafayate', 'Embarcación',
    'Rivadavia', 'La Caldera',
  ],
  'Entre Ríos': [
    'Paraná', 'Concordia', 'Gualeguaychú', 'Concepción del Uruguay',
    'Colón', 'Victoria', 'Villaguay', 'La Paz', 'Chajarí', 'Crespo',
    'Nogoyá', 'Federal', 'Federación',
  ],
  'Misiones': [
    'Posadas', 'Oberá', 'Eldorado', 'Puerto Iguazú', 'Apóstoles',
    'Leandro N. Alem', 'San Vicente', 'Montecarlo', 'Jardín América',
    'San Pedro', 'Aristóbulo del Valle', 'Capioví',
  ],
  'Chaco': [
    'Resistencia', 'Presidencia Roque Sáenz Peña', 'Villa Ángela',
    'Barranqueras', 'Charata', 'Las Breñas', 'General San Martín',
    'Quitilipi', 'Fontana', 'Juan José Castelli',
  ],
  'Corrientes': [
    'Corrientes', 'Goya', 'Paso de los Libres', 'Curuzú Cuatiá',
    'Santo Tomé', 'Bella Vista', 'Mercedes', 'Monte Caseros',
    'Yapeyú', 'Empedrado', 'Mburucuyá',
  ],
  'Santiago del Estero': [
    'Santiago del Estero', 'La Banda', 'Termas de Río Hondo', 'Frías',
    'Añatuya', 'Loreto', 'Quimilí', 'Villa Atamisqui',
  ],
  'San Juan': [
    'San Juan', 'Rawson', 'Rivadavia', 'Caucete', 'Chimbas',
    'Santa Lucía', 'Pocito', 'Sarmiento', 'Albardón', '9 de Julio',
  ],
  'Jujuy': [
    'San Salvador de Jujuy', 'Palpalá', 'San Pedro', 'Libertador General San Martín',
    'Tilcara', 'Humahuaca', 'La Quiaca', 'Perico', 'El Carmen',
  ],
  'Río Negro': [
    'Viedma', 'Bariloche', 'General Roca', 'Cipolletti', 'Allen',
    'Cinco Saltos', 'Catriel', 'El Bolsón', 'Choele Choel', 'Villa Regina',
    'Ingeniero Jacobacci', 'Sierra Grande',
  ],
  'Neuquén': [
    'Neuquén', 'Centenario', 'Plottier', 'Zapala', 'San Martín de los Andes',
    'Cutral-Có', 'Plaza Huincul', 'Junín de los Andes', 'Chos Malal', 'Rincón de los Sauces',
  ],
  'Formosa': [
    'Formosa', 'Clorinda', 'Pirané', 'El Colorado', 'Ingeniero Juárez',
    'Laguna Blanca', 'General Lucio Victorio Mansilla',
  ],
  'La Pampa': [
    'Santa Rosa', 'General Pico', 'Toay', 'Realicó', 'Victorica',
    'Eduardo Castex', 'General Acha', 'Macachín', 'Trenque Lauquen',
  ],
  'Chubut': [
    'Rawson', 'Comodoro Rivadavia', 'Trelew', 'Puerto Madryn', 'Esquel',
    'Rada Tilly', 'Dolavon', 'Gaiman', 'Sarmiento', 'Lago Puelo',
  ],
  'San Luis': [
    'San Luis', 'Villa Mercedes', 'Merlo', 'Buena Esperanza', 'Villa Dolores',
    'Arizona', 'La Toma', 'Quines',
  ],
  'Catamarca': [
    'San Fernando del Valle de Catamarca', 'Tinogasta', 'Andalgalá',
    'Belén', 'Recreo', 'Santa María', 'Fiambalá',
  ],
  'La Rioja': [
    'La Rioja', 'Chilecito', 'Arauco', 'Chamical', 'Aimogasta',
    'Villa Unión', 'Chepes',
  ],
  'Santa Cruz': [
    'Río Gallegos', 'Caleta Olivia', 'Pico Truncado', 'El Calafate',
    'Las Heras', 'Puerto Deseado', 'Puerto San Julián', 'Gobernador Gregores',
  ],
  'Tierra del Fuego': [
    'Ushuaia', 'Río Grande', 'Tolhuin',
  ],
}
