export const ARGENTINA_PROVINCES = [
  'Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Ciudad Autónoma de Buenos Aires',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán',
]

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  'Buenos Aires': [
    // GBA Norte
    'San Isidro', 'Vicente López', 'San Fernando', 'Tigre', 'Pilar', 'Escobar',
    'Malvinas Argentinas', 'San Miguel', 'Hurlingham', 'Ituzaingó', 'Tres de Febrero',
    'General San Martín', 'José C. Paz', 'Moreno', 'Merlo',
    // GBA Sur
    'La Plata', 'Quilmes', 'Lanús', 'Lomas de Zamora', 'Almirante Brown',
    'La Matanza', 'Morón', 'Avellaneda', 'Berazategui', 'Florencio Varela',
    'Esteban Echeverría', 'Ezeiza', 'Berisso', 'Ensenada', 'San Vicente',
    'Presidente Perón', 'Marcos Paz',
    // Interior bonaerense
    'Bahía Blanca', 'Mar del Plata', 'Tandil', 'Olavarría', 'Junín',
    'Pergamino', 'San Nicolás de los Arroyos', 'Zárate', 'Campana', 'Luján',
    'Mercedes', 'Chivilcoy', 'Bragado', 'Lincoln', 'Pehuajó', 'Trenque Lauquen',
    'Necochea', 'Tres Arroyos', 'Azul', 'Chascomús', 'Dolores',
    'Balcarce', 'Coronel Suárez', 'Benito Juárez', 'Lobos', 'Navarro',
    'Saladillo', 'Las Flores', '25 de Mayo', 'Roque Pérez', 'General Alvear',
    'Tapalqué', 'Rauch', 'Ayacucho', 'General Madariaga', 'Pinamar', 'Villa Gesell',
    'Mar Chiquita', 'Miramar', 'General Pueyrredón', 'General Alvarado',
    'Maipú', 'Lobería', 'San Cayetano', '9 de Julio', 'Carlos Casares',
    'Rivadavia', 'Alberti', 'Chacabuco', 'General Viamonte', 'Leandro N. Alem',
    'Salto', 'Rojas', 'Ramallo', 'San Pedro', 'Baradero', 'Arrecifes',
    'Capitán Sarmiento', 'San Antonio de Areco', 'Exaltación de la Cruz',
    'Gral. Rodríguez', 'Cañuelas', 'General Las Heras', 'Patagones', 'Villarino',
    'Tornquist', 'Puan', 'Guaminí', 'Daireaux', 'Hipólito Yrigoyen',
    'Bolívar', 'General La Madrid', 'Laprida',
  ],
  'Ciudad Autónoma de Buenos Aires': [
    'Almagro', 'Balvanera', 'Barracas', 'Belgrano', 'Boedo',
    'Caballito', 'Chacarita', 'Coghlan', 'Colegiales', 'Constitución',
    'Flores', 'Floresta', 'La Boca', 'La Paternal', 'Liniers',
    'Mataderos', 'Microcentro', 'Monte Castro', 'Montserrat',
    'Nueva Pompeya', 'Núñez', 'Palermo', 'Parque Avellaneda',
    'Parque Chacabuco', 'Parque Chas', 'Parque Patricios', 'Puerto Madero',
    'Recoleta', 'Retiro', 'Saavedra', 'San Cristóbal', 'San Nicolás',
    'San Telmo', 'Versalles', 'Villa Crespo', 'Villa del Parque',
    'Villa Devoto', 'Villa Lugano', 'Villa Luro', 'Villa Ortúzar',
    'Villa Pueyrredón', 'Villa Real', 'Villa Riachuelo', 'Villa Santa Rita',
    'Villa Soldati', 'Villa Urquiza', 'Villa Vélez Sarsfield',
  ],
  'Córdoba': [
    'Córdoba', 'Villa María', 'Río Cuarto', 'San Francisco', 'Alta Gracia',
    'Jesús María', 'Villa Carlos Paz', 'Bell Ville', 'Marcos Juárez',
    'Villa Allende', 'Cosquín', 'La Calera', 'Río Tercero', 'Oncativo',
    'Río Segundo', 'Dean Funes', 'Cruz del Eje', 'Laboulaye',
    'Leones', 'Pilar', 'Villa Dolores', 'Cruz Alta',
    'James Craik', 'Oliva', 'Arroyito', 'Despeñaderos',
    'Río Ceballos', 'Unquillo', 'Mendiolaza', 'Saldán', 'Malagueño',
    'Falda del Carmen', 'Anisacate', 'Santa Rosa de Calamuchita',
    'Villa General Belgrano', 'Mina Clavero', 'Nono', 'Traslasierra',
    'Embalse', 'Berrotarán', 'Las Varillas', 'San Marcos Sierras',
    'Colonia Caroya', 'Sinsacate', 'Villa del Totoral', 'Capilla del Monte',
    'La Cumbre', 'Cruz de Eje', 'Deán Funes', 'Serrano', 'Hernando',
    'General Cabrera', 'Monte Maíz', 'Etruria', 'Carrilobo',
    'Corral de Bustos', 'Inriville', 'Noetinger', 'Canals', 'Italó',
    'Villa del Rosario', 'Monte Cristo', 'Obispo Trejo', 'Miramar',
    'Juárez Celman', 'Balnearia', 'San José de la Dormida',
  ],
  'Santa Fe': [
    'Rosario', 'Santa Fe', 'Rafaela', 'Venado Tuerto', 'San Lorenzo',
    'Reconquista', 'Casilda', 'Villa Constitución', 'Firmat', 'Gálvez',
    'Esperanza', 'Santo Tomé', 'Capitán Bermúdez', 'Cañada de Gómez',
    'Carcarañá', 'Las Rosas', 'Rufino', 'Vera', 'Tostado',
    'Sunchales', 'Laguna Paiva', 'Correa', 'Armstrong', 'Pérez',
    'Recreo', 'Sauce Viejo', 'Rincón', 'San Jerónimo del Sauce',
    'Sastre', 'Montes de Oca', 'Totoras', 'Bernardo de Irigoyen',
    'Las Parejas', 'Las Petacas', 'Bouquet', 'María Juana',
    'Ceres', 'San Cristóbal', 'Moisés Ville', 'Hersilia', 'Calchaquí',
    'Los Cardos', 'Roldan', 'Funes', 'Soldini', 'Roldán', 'Alvear',
    'Villa Gobernador Gálvez', 'Granadero Baigorria', 'Soldado Aldea',
    'Pueblo Esther', 'General Lagos', 'Arroyo Seco', 'Fighiera',
    'Puerto General San Martín', 'Timbúes', 'San Genaro', 'Alcorta',
    'Melincué', 'Laborde', 'Elortondo', 'Hughes', 'General Ramírez',
    'Aarón Castellanos', 'Chapuy', 'Máximo Paz', 'Pavón', 'Theobald',
  ],
  'Mendoza': [
    'Mendoza', 'San Rafael', 'Maipú', 'Luján de Cuyo', 'Godoy Cruz',
    'Guaymallén', 'Las Heras', 'Rivadavia', 'Tunuyán', 'General Alvear',
    'Junín', 'La Paz', 'Malargüe', 'San Martín', 'Santa Rosa',
    'Lavalle', 'Palmira', 'Ciudad', 'Dorrego', 'El Sosneado',
    'Alvear', 'Villa Atuel', 'Real del Padre', 'Bowen', 'Carmensa',
    'Perdriel', 'Agrelo', 'Ugarteche', 'Drummond', 'Rodeo del Medio',
    'Medrano', 'Montecaseros', 'González Moreno', 'Rama Caída',
    'Las Catitas', 'Tres Porteñas', 'Chilecito', 'Potrerillos',
    'Chacras de Coria', 'Vistalba', 'Mayor Drummond', 'Luzuriaga',
    'San José', 'Russell', 'Eugenio Bustos', 'La Consulta',
  ],
  'Tucumán': [
    'San Miguel de Tucumán', 'Yerba Buena', 'Tafí Viejo', 'Concepción',
    'Banda del Río Salí', 'Aguilares', 'Alderetes', 'Famaillá',
    'Monteros', 'Lules', 'Bella Vista', 'Simoca', 'Graneros',
    'Trancas', 'Burruyacú', 'Juan Bautista Alberdi', 'Acheral',
    'Santa Lucía', 'Río Seco', 'Tafí del Valle', 'Amaicha del Valle',
    'Quilmes', 'El Cadillal', 'Raco', 'Las Talitas', 'El Manantial',
    'San Pablo', 'La Reducción', 'Villa Quinteros',
    'Los Ralos', 'Chicligasta', 'Los Sarmientos',
  ],
  'Salta': [
    'Salta', 'Orán', 'Tartagal', 'Metán', 'Rosario de la Frontera',
    'Güemes', 'Cerrillos', 'General Güemes', 'Cafayate', 'Embarcación',
    'Rivadavia', 'La Caldera', 'Campo Santo', 'Joaquín V. González',
    'Las Lajitas', 'Pichanal', 'Aguaray', 'Salvador Mazza',
    'Cachi', 'Molinos', 'Animaná', 'Angastaco', 'San Antonio de los Cobres',
    'Rosario de Lerma', 'El Bordo', 'Hickmann', 'Apolinario Saravia',
    'Colonia Santa Rosa', 'Plumas', 'Payogasta', 'La Poma',
    'Los Blancos', 'Morillo', 'Rivadavia Banda Norte', 'Coronel Cornejo',
  ],
  'Jujuy': [
    'San Salvador de Jujuy', 'Palpalá', 'San Pedro', 'Libertador General San Martín',
    'Tilcara', 'Humahuaca', 'La Quiaca', 'Perico', 'El Carmen',
    'Maimará', 'Purmamarca', 'Susques', 'Abra Pampa', 'Rinconada',
    'Santa Catalina', 'Yavi', 'Calilegua', 'Fraile Pintado',
    'Monterrico', 'León', 'El Aguilar', 'Tres Cruces',
    'San Francisco', 'Valle Grande', 'Santa Bárbara',
  ],
  'Entre Ríos': [
    'Paraná', 'Concordia', 'Gualeguaychú', 'Concepción del Uruguay',
    'Colón', 'Victoria', 'Villaguay', 'La Paz', 'Chajarí', 'Crespo',
    'Nogoyá', 'Federal', 'Federación', 'Diamante', 'San José',
    'Gualeguay', 'Rosario del Tala', 'Basavilbaso', 'Bovril',
    'El Tigre', 'Pronunciamiento', 'San Gustavo', 'Gilbert',
    'Ramírez', 'Hernández', 'Aldea Brasilera', 'Viale', 'Maciá',
    'Urdinarrain', 'Ibicuy', 'General Ramírez', 'Pueblo General Belgrano',
    'Caseros', 'Cerrito', 'Larroque', 'Gobernador Mansilla',
    'Lucas González', 'Aranguren',
  ],
  'Misiones': [
    'Posadas', 'Oberá', 'Eldorado', 'Puerto Iguazú', 'Apóstoles',
    'Leandro N. Alem', 'San Vicente', 'Montecarlo', 'Jardín América',
    'San Pedro', 'Aristóbulo del Valle', 'Capioví', 'Wanda',
    'Puerto Esperanza', 'Puerto Rico', 'Iguazú', 'Colonia Aurora',
    'Campo Grande', 'Garuhapé', 'Capiovi', 'El Soberbio', 'San Javier',
    'Concepción de la Sierra', 'Santa Ana', 'Candelaria', 'Loreto',
    'San Ignacio', 'Corpus', 'Itacaruaré', 'Alba Posse',
    'Bernardo de Irigoyen', 'San Antonio', 'Dos de Mayo',
    'Colonia Alberdi', 'Profundidad', 'Roca Chica',
  ],
  'Chaco': [
    'Resistencia', 'Presidencia Roque Sáenz Peña', 'Villa Ángela',
    'Barranqueras', 'Charata', 'Las Breñas', 'General San Martín',
    'Quitilipi', 'Fontana', 'Juan José Castelli', 'Villa Berthet',
    'Campo Largo', 'Machagai', 'Pinedo', 'Corzuela', 'Tres Isletas',
    'La Escondida', 'Coronel Du Graty', 'Pampa Almirón', 'Napenay',
    'Cote Lai', 'La Verde', 'Makallé', 'Avia Terai', 'Pampa del Infierno',
    'Taco Pozo', 'Los Frentones', 'Miraflores', 'Misión Nueva Pompeya',
    'Santa Sylvina', 'Hermoso Campo', 'General Vedia',
    'Lapachito', 'Capitán Solari', 'Colonia Benítez',
  ],
  'Corrientes': [
    'Corrientes', 'Goya', 'Paso de los Libres', 'Curuzú Cuatiá',
    'Santo Tomé', 'Bella Vista', 'Mercedes', 'Monte Caseros',
    'Yapeyú', 'Empedrado', 'Mburucuyá', 'Ituzaingó', 'Posadas',
    'San Luis del Palmar', 'Saladas', 'Concepción', 'Esquina',
    'Sauce', 'Lavalle', 'Santa Lucía', 'La Cruz', 'Alvear',
    'Gobernador Valentín Virasoro', 'General Alvear', 'Caá Catí',
    'Berón de Astrada', 'General Paz', 'Itatí', 'Loreto',
    'San Roque', 'Chavarría', 'Perugorría', 'Tatacuá',
    'Mocoretá', 'Mariano I. Loza',
  ],
  'Santiago del Estero': [
    'Santiago del Estero', 'La Banda', 'Termas de Río Hondo', 'Frías',
    'Añatuya', 'Loreto', 'Quimilí', 'Villa Atamisqui',
    'Suncho Corral', 'Bandera', 'Monte Quemado', 'Tintina',
    'Pinto', 'Clodomira', 'Real Sayana', 'Beltrán', 'Campo Gallo',
    'Pampa de los Guanacos', 'Colonia Dora', 'Villa Ojo de Agua',
    'Selva', 'Hualfín', 'Garza', 'Icaño', 'Tramo 16',
    'Pozo Hondo', 'Sumampa', 'El Bobadal', 'Laprida',
    'San Pedro de Guasayán', 'Antilo', 'Fernández', 'Llajta Mauca',
  ],
  'San Juan': [
    'San Juan', 'Rawson', 'Rivadavia', 'Caucete', 'Chimbas',
    'Santa Lucía', 'Pocito', 'Sarmiento', 'Albardón', '9 de Julio',
    'Angaco', 'Valle Fértil', 'Ullum', 'Zonda', 'Calingasta',
    'Iglesia', 'Jachal', 'Rodeo', 'Huaco', 'Pismanta',
    'Villa Krause', 'Marquesado', 'Colonia Fiorito', 'Médano de Oro',
    'Pie de Palo', 'Las Tumanas', 'Barreal',
  ],
  'San Luis': [
    'San Luis', 'Villa Mercedes', 'Merlo', 'Buena Esperanza',
    'La Toma', 'Quines', 'Concarán', 'Naschel',
    'Juana Koslay', 'El Trapiche', 'Tilisarao', 'San Francisco del Monte de Oro',
    'Luján', 'Santa Rosa del Conlara', 'Papagayos', 'Renca',
    'Anchorena', 'Unión', 'Fortuna', 'Justo Daract',
    'Arizona', 'Desaguadero',
  ],
  'La Pampa': [
    'Santa Rosa', 'General Pico', 'Toay', 'Realicó', 'Victorica',
    'Eduardo Castex', 'General Acha', 'Macachín', 'Winifreda',
    'Intendente Alvear', 'Colonia Barón', 'Catriló', 'Quemú Quemú',
    'Bernasconi', 'Guatraché', 'Doblas', 'Ingeniero Luiggi',
    'Anguil', 'Pichi Huinca', 'Caleufú', 'Sarah', 'Speluzzi',
    'Alta Italia', 'Rancul', 'Jacinto Arauz', 'Uriburu',
    'Embajador Martini', 'General Campos', 'La Adela', 'Puelén',
    'Santa Isabel', 'Chacharramendi', 'La Reforma', 'Lonquimay',
    'Alpachiri', 'Miguel Riglos', 'Trenel', '25 de Mayo',
    'Quetrequén', 'Conhelo', 'Rolón', 'Loventué', 'Limay Mahuida',
    'Cuchillo-Có', 'General San Martín', 'La Humada', 'Lihué Calel',
    'Metileo', 'Miramar', 'Ojeda', 'Parera', 'Perú', 'Puelches',
    'Telén', 'Vértiz', 'Abramo', 'Agustoni', 'Algarrobo del Águila',
    'Arata', 'Ataliva Roca', 'Capdevila',
  ],
  'La Rioja': [
    'La Rioja', 'Chilecito', 'Arauco', 'Chamical', 'Aimogasta',
    'Villa Unión', 'Chepes', 'Famatina', 'Nonogasta', 'Pagancillo',
    'Vinchina', 'Villa Castelli', 'San Blas de los Sauces',
    'Olta', 'General Ángel Vicente Peñaloza', 'Patquía',
    'Añatuya', 'Tama', 'Castro Barros', 'Pinchas',
    'Chuquis', 'Guandacol', 'Tinogasta',
  ],
  'Catamarca': [
    'San Fernando del Valle de Catamarca', 'Tinogasta', 'Andalgalá',
    'Belén', 'Recreo', 'Santa María', 'Fiambalá',
    'Hualfín', 'Pomán', 'Fray Mamerto Esquiú', 'El Rodeo',
    'Ancasti', 'Chumbicha', 'Icaño', 'San Pedro', 'Chañar Punco',
    'Villa de Antinaco', 'Londres', 'Saujil', 'Santa Cruz',
    'Los Altos', 'Aconquija', 'Miraflores',
  ],
  'Neuquén': [
    'Neuquén', 'Centenario', 'Plottier', 'Zapala', 'San Martín de los Andes',
    'Cutral-Có', 'Plaza Huincul', 'Junín de los Andes', 'Chos Malal',
    'Rincón de los Sauces', 'Villa La Angostura', 'Caviahue', 'Copahue',
    'Las Lajas', 'Senillosa', 'Vista Alegre', 'Añelo', 'Picún Leufú',
    'Loncopué', 'Las Coloradas', 'Aluminé', 'Villa Pehuenia',
    'Manzano Amargo', 'Buta Ranquil', 'Barrancas', 'Andacollo',
    'Tricao Malal', 'El Cholar', 'Varvarco', 'Taquimilán',
    'Quili Malal', 'Chorriaca', 'Las Ovejas', 'Ñorquín',
  ],
  'Río Negro': [
    'Viedma', 'Bariloche', 'General Roca', 'Cipolletti', 'Allen',
    'Cinco Saltos', 'Catriel', 'El Bolsón', 'Choele Choel', 'Villa Regina',
    'Ingeniero Jacobacci', 'Sierra Grande', 'San Antonio Oeste',
    'Río Colorado', 'Fernández Oro', 'Campo Grande', 'Lamarque',
    'Conesa', 'Darwin', 'Belisle', 'Chimpay', 'Contralmirante Cordero',
    'Luis Beltrán', 'Pomona', 'Villa El Chocón', 'Ñorquinco',
    'El Cuy', 'Pilcaniyeu', 'Bariloche', 'Dina Huapi',
    'El Maitén', 'Ñorquinco', 'Comallo', 'Mencue', 'Pilquiniyeu del Lago',
    'Valcheta', 'Los Menucos', 'Maquinchao',
  ],
  'Chubut': [
    'Rawson', 'Comodoro Rivadavia', 'Trelew', 'Puerto Madryn', 'Esquel',
    'Rada Tilly', 'Dolavon', 'Gaiman', 'Sarmiento', 'Lago Puelo',
    'El Maitén', 'Epuyén', 'Cholila', 'Tecka', 'Gobernador Costa',
    'Las Plumas', 'Paso de Indios', 'Rio Senguer', 'Facundo',
    'Puerto Pirámides', 'Camarones', 'Caleta Olivia',
    'Río Mayo', 'Alto Río Senguer', 'Aldea Apeleg', 'Gualjaina',
    'El Hoyo', 'El Maitén', 'Cushamen',
  ],
  'Santa Cruz': [
    'Río Gallegos', 'Caleta Olivia', 'Pico Truncado', 'El Calafate',
    'Las Heras', 'Puerto Deseado', 'Puerto San Julián', 'Gobernador Gregores',
    'Perito Moreno', 'Los Antiguos', 'El Chaltén', 'Comandante Luis Piedrabuena',
    'Puerto Santa Cruz', 'Tres Lagos', 'Hipólito Yrigoyen', 'Koluel Kayke',
    'Jaramillo', 'Fitz Roy', 'Tellier',
  ],
  'Formosa': [
    'Formosa', 'Clorinda', 'Pirané', 'El Colorado', 'Ingeniero Juárez',
    'Laguna Blanca', 'General Lucio Victorio Mansilla', 'Las Lomitas',
    'Ibarreta', 'General Mosconi', 'Villa Dos Trece', 'Subteniente Perín',
    'Comandante Fontana', 'Pozo del Tigre', 'Palo Santo', 'General Enrique Mosconi',
    'Herradura', 'Portón Negro', 'Siete Palmas',
  ],
  'Tierra del Fuego': [
    'Ushuaia', 'Río Grande', 'Tolhuin', 'Las Cotorras',
  ],
}
