import type { PluginDefinition } from '@/types'

export const PLUGIN_DEFINITIONS: PluginDefinition[] = [
  {
    id: 'email-campaigns',
    name: 'Campañas de Email',
    description: 'Envío de campañas de email masivo — ya es parte del módulo Comunicaciones, disponible siempre, sin depender de este interruptor.',
    icon: 'Mail',
    category: 'communication',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: false,
  },
  {
    id: 'export-data',
    name: 'Exportación de Datos',
    description: 'Exportar clientes, facturas y reportes a XLS/CSV con un botón directo en cada listado. Todavía no está construido.',
    icon: 'Download',
    category: 'productivity',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: false,
  },
  {
    id: 'global-search',
    name: 'Búsqueda Global',
    description: 'El buscador de la barra superior — ya está siempre activo para todo el equipo, no depende de este interruptor.',
    icon: 'Search',
    category: 'productivity',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: false,
  },
  {
    id: 'advanced-analytics',
    name: 'Analíticas Avanzadas',
    description: 'Agrega la sección "Top Clientes por Ingreso" al Dashboard.',
    icon: 'BarChart3',
    category: 'analytics',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: true,
  },
  {
    id: 'whatsapp-integration',
    name: 'WhatsApp Business',
    description: 'Enviar mensajes de WhatsApp desde la ficha de un cliente vía la API de WhatsApp Business. Todavía no está construido.',
    icon: 'MessageCircle',
    category: 'communication',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: true,
    configSchema: {
      apiToken: { type: 'string', label: 'WhatsApp API Token', required: true },
      phoneNumberId: { type: 'string', label: 'Phone Number ID', required: true },
    },
    implemented: false,
  },
  {
    id: 'invoice-automation',
    name: 'Facturación Automática',
    description: 'Generar y enviar facturas automáticamente según contratos recurrentes. Hoy existe "Generar Facturas del Mes" en Facturación, pero manual — este automatizado todavía no está construido.',
    icon: 'FileText',
    category: 'productivity',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: false,
  },
  {
    id: 'zapier-webhooks',
    name: 'Zapier / Webhooks',
    description: 'Conectar el CRM con otras aplicaciones vía Zapier o webhooks propios. Todavía no está construido.',
    icon: 'Zap',
    category: 'integration',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: true,
    configSchema: {
      webhookUrl: { type: 'string', label: 'Webhook URL', required: false },
    },
    implemented: false,
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Sincronizar reuniones y tareas del CRM con Google Calendar. Todavía no está construido.',
    icon: 'Calendar',
    category: 'integration',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: true,
    configSchema: {
      clientId: { type: 'string', label: 'Google Client ID', required: true },
    },
    implemented: false,
  },
]

export function getPlugin(id: string): PluginDefinition | undefined {
  return PLUGIN_DEFINITIONS.find((p) => p.id === id)
}
