import type { PluginDefinition } from '@/types'

export const PLUGIN_DEFINITIONS: PluginDefinition[] = [
  {
    id: 'export-data',
    name: 'Exportación de Datos',
    description: 'Agrega un botón "Exportar" en Empresas y Facturas para bajar a Excel (.xlsx) todo lo que matchea los filtros activos.',
    icon: 'Download',
    category: 'productivity',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: true,
  },
  {
    id: 'advanced-analytics',
    name: 'Analíticas Avanzadas',
    description: 'Agrega la sección "Top Clientes por Ingreso" al Dashboard.',
    icon: 'BarChart3',
    category: 'analytics',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: true,
  },
  {
    id: 'whatsapp-integration',
    name: 'WhatsApp Business',
    description: 'Agrega un botón "Enviar WhatsApp" en la ficha de contacto, que manda el mensaje vía la API de WhatsApp Business de Meta. Necesitás una cuenta de WhatsApp Business API (Meta for Developers) — sin el API Token y el Phone Number ID cargados acá abajo, el botón no aparece.',
    icon: 'MessageCircle',
    category: 'communication',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: true,
    configSchema: {
      apiToken: { type: 'password', label: 'WhatsApp API Token', required: true },
      phoneNumberId: { type: 'string', label: 'Phone Number ID', required: true },
    },
    implemented: true,
  },
  {
    id: 'invoice-automation',
    name: 'Facturación Automática',
    description: 'El día 1 de cada mes genera solas las facturas de los clientes con monto mensual cargado (mismo criterio que "Generar del Mes", pero automático) y te avisa por mail lo que se generó. No las envía al cliente — quedan como Pendiente para que las revises antes de avisarle a cada uno.',
    icon: 'FileText',
    category: 'productivity',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: true,
  },
  {
    id: 'zapier-webhooks',
    name: 'Zapier / Webhooks',
    description: 'Manda un POST con los datos del evento a la URL que cargues cada vez que se gana una oportunidad, se cobra una factura o entra un ticket nuevo — para conectar con Zapier, Make o tu propio endpoint.',
    icon: 'Zap',
    category: 'integration',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: true,
    configSchema: {
      webhookUrl: { type: 'string', label: 'Webhook URL', required: false },
    },
    implemented: true,
  },
  {
    id: 'attendance-alerts',
    name: 'Avisos de Asistencia',
    description: 'Manda un mail diario a ADMIN/SUPER_ADMIN/RRHH con quién no fichó o llegó tarde el último día hábil. Apagado por defecto — activalo sólo si tu equipo quiere que RRHH reciba este aviso automático.',
    icon: 'Bell',
    category: 'productivity',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: false,
    implemented: true,
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Conectá una cuenta de Google (OAuth) y agregá tareas del CRM a tu Google Calendar con un botón desde la ficha de la tarea. Necesitás crear una app OAuth en Google Cloud Console con el redirect URI que te mostramos al conectar — sin Client ID y Client Secret cargados acá abajo, no se puede iniciar la conexión.',
    icon: 'Calendar',
    category: 'integration',
    version: '1.0.0',
    author: 'CRM Core',
    requiresConfig: true,
    configSchema: {
      clientId: { type: 'string', label: 'Google Client ID', required: true },
      clientSecret: { type: 'password', label: 'Google Client Secret', required: true },
    },
    implemented: true,
  },
]

export function getPlugin(id: string): PluginDefinition | undefined {
  return PLUGIN_DEFINITIONS.find((p) => p.id === id)
}
